package com.tgac.logic.finitedomain.domains;
// Generated by CodiumAI

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import com.tgac.logic.finitedomain.Domain;
import com.tgac.logic.finitedomain.Ints;
import io.vavr.collection.Array;
import org.assertj.core.api.Assertions;
import org.junit.Test;

public class UnionTest {

	@Test
	public void shouldMergeNonOverlappingDomains() {
		// Create two non-overlapping domains
		Domain<Integer> domain1 = Ints.interval(1, 3);
		Domain<Integer> domain2 = Ints.interval(4, 6);

		// Create an array of the two domains
		Array<Domain<Integer>> intervals = Array.of(domain1, domain2);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single domain with the expected values
		assertEquals(1, mergedDomains.size());
		assertEquals(
				Ints.interval(1, 6),
				mergedDomains.get(0));
	}

	@Test
	public void test_mergeOverlappingDomains() {
		// Create two overlapping domains
		Domain<Integer> domain1 = Ints.interval(1, 3);
		Domain<Integer> domain2 = Ints.interval(3, 5);

		// Create an array of the two domains
		Array<Domain<Integer>> intervals = Array.of(domain1, domain2);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single domain with the expected values
		assertEquals(1, mergedDomains.size());
		assertEquals(Ints.interval(1, 5), mergedDomains.get(0));
	}

	@Test
	public void shouldMergeMultipleOverlappingDomains() {
		// Create three overlapping domains
		Domain<Integer> domain1 = Ints.interval(1, 3);
		Domain<Integer> domain2 = Ints.interval(3, 5);
		Domain<Integer> domain3 = Ints.interval(5, 7);

		// Create an array of the three domains
		Array<Domain<Integer>> intervals = Array.of(domain1, domain2, domain3);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single domain with the expected values
		assertEquals(1, mergedDomains.size());
		assertEquals(Ints.interval(1, 7), mergedDomains.get(0));
	}

	@Test
	public void shouldMergeSingletons() {
		// Create two overlapping domains
		Domain<Integer> domain1 = Ints.singleton(1);
		Domain<Integer> domain2 = Ints.singleton(1);

		// Create an array of the two domains
		Array<Domain<Integer>> intervals = Array.of(domain1, domain2);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single domain with the expected values
		assertEquals(1, mergedDomains.size());
		assertEquals(Ints.singleton(1), mergedDomains.get(0));
	}

	@Test
	public void shouldMergeConsecutiveSingletons() {
		// Create two overlapping domains
		Domain<Integer> domain1 = Ints.singleton(1);
		Domain<Integer> domain2 = Ints.singleton(2);

		// Create an array of the two domains
		Array<Domain<Integer>> intervals = Array.of(domain1, domain2);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single domain with the expected values
		assertEquals(1, mergedDomains.size());
		assertEquals(Ints.interval(1, 2), mergedDomains.get(0));
	}

	@Test
	public void shouldMergeEmptyArray() {
		// Create an empty array of domains
		Array<Domain<Integer>> intervals = Array.empty();

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array is empty
		assertTrue(mergedDomains.isEmpty());
	}

	@Test
	public void shouldRemoveEmptyDomains() {
		// Create a single empty domain
		Domain<Integer> domain = Empty.instance();

		// Create an array with the empty domain
		Array<Domain<Integer>> intervals = Array.of(domain);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single empty domain
		assertEquals(0, mergedDomains.size());
	}

	@Test
	public void shouldMergeSingleDomain() {
		// Create a single domain
		Domain<Integer> domain = Ints.interval(1, 3);

		// Create an array with the domain
		Array<Domain<Integer>> intervals = Array.of(domain);

		// Call the mergeOverlappingDomains method
		Array<Domain<Integer>> mergedDomains = Union.mergeOverlappingIntervals(intervals);

		// Assert that the mergedDomains array contains a single domain with the expected values
		assertEquals(1, mergedDomains.size());
		assertEquals(domain, mergedDomains.get(0));
	}

	@Test
	public void shouldContainValue() {
		Domain<Integer> domain1 = Ints.interval(1, 5);
		Domain<Integer> domain2 = Ints.interval(10, 15);

		Union<Integer> union = Union.of(domain1, domain2);

		assertTrue(union.contains(3));
		assertFalse(union.contains(7));
	}

	@Test
	public void shouldStreamValues() {
		Domain<Integer> domain1 = Ints.interval(1, 5);
		Domain<Integer> domain2 = Ints.interval(10, 15);

		Union<Integer> union = Union.of(domain1, domain2);

		assertEquals(Array.of(1, 2, 3, 4, 5, 10, 11, 12, 13, 14, 15),
				union.stream().collect(Array.collector()));
	}

	@Test
	public void shouldCreateMultiIntervalFromEmptyArray() {
		Union<Integer> union = Union.of();

		assertTrue(union.getIntervals().isEmpty());
	}

	@Test
	public void shouldCreateMultiIntervalFromArrayOfEmptyDomains() {
		Empty<Integer> empty1 = Empty.instance();
		Empty<Integer> emptyDomain2 = Empty.instance();

		Union<Integer> union = Union.of(empty1, emptyDomain2);

		assertTrue(union.getIntervals().isEmpty());
	}

	@Test
	public void shouldDiffSimple() {
		Assertions.assertThat(
						Union.of(
										Ints.interval(0, 10),
										Ints.interval(20, 30))
								.difference(Ints.interval(5, 25)))
				.isEqualTo(
						Union.of(
								Ints.interval(0, 4),
								Ints.interval(26, 30)));
	}

	@Test
	public void shouldDiffEnumerated() {
		Assertions.assertThat(
						Union.of(
										Ints.interval(0, 10),
										Ints.interval(20, 30))
								.difference(Ints.enumerated(5, 15, 25)))
				.isEqualTo(
						Union.of(
								Ints.interval(0, 4),
								Ints.interval(6, 10),
								Ints.interval(20, 24),
								Ints.interval(26, 30)));
	}

}